# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26177369c57934cdea32a1d5c1c01f5c21901f16c97b93fa829742aa884698054cdd3ec6aa2851f0400d8873791eeb597de0b51f6ad831b9c30e69979b08a373

test:
  secret_key_base: 48ec6b78855e231c4c181d8d7e2101ea02d28078065eff16ce5b24bc9fefd43ebfc6b0e03fd1035b32d6494fb4426ec52773741fa97e04e9f62e828352f5cf04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
